node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v2/', 'ddc4d2e0-09d7-4c82-aa57-3a0a8d00d9ef') {
       def app = docker.build("lintao0o0/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
